### get csrf token
GET http://localhost:8080/csrf
Authorization: Basic {{base64_username_password}}

> {% client.global.set("csrf_token", response.body.csrfToken); %}

### Get trades sorted
### Unsorted Call: /v1/api/trades/sorted?page=0&size=10
### Sorted by Price (Descending): /v1/api/trades/sorted?page=0&size=10&sort=price,desc
### Sorted by Trade Type (Ascending): /v1/api/trades/sorted?page=0&size=10&sort=tradeType,asc
GET http://localhost:8080/v1/api/trades?page=0&size=10
Content-Type: application/json
Authorization: Basic {{base64_username_password}}
X-CSRF-TOKEN: {{csrf_token}}

### Get trade by ID
GET http://localhost:8080/v1/api/trades/2
Authorization: Basic {{base64_username_password}}
X-CSRF-TOKEN: {{csrf_token}}

### Get trades by portfolio ID (paginated)
GET http://localhost:8080/v1/api/trades/portfolio/1?page=0&size=10&sort=price,desc
Authorization: Basic {{base64_username_password}}
X-CSRF-TOKEN: {{csrf_token}}

### Submit a trade
POST http://localhost:8080/v1/api/trades
Content-Type: application/json
Authorization: Basic {{base64_username_password}}
X-CSRF-TOKEN: {{csrf_token}}

{
  "portfolioId": 1,
  "tradeReferenceId": "TREF124",
  "tradeType": "SELL",
  "quantity": 50,
  "price": 51.00,
  "status": "PENDING"
}

### Update a trade
PUT http://localhost:8080/v1/api/trades/update/1
Content-Type: application/json
Authorization: Basic {{base64_username_password}}
X-CSRF-TOKEN: {{csrf_token}}

{
  "portfolioId": 1,
  "tradeReferenceId": "TREF125",
  "tradeType": "BUY",
  "quantity": 120,
  "price": 50.50,
  "status": "COMPLETED"
}

### Delete a trade
DELETE http://localhost:8080/v1/api/trades/delete/7
Authorization: Basic {{base64_username_password}}
X-CSRF-TOKEN: {{csrf_token}}